[project]
name = "mlpad"
version = "0.1.0"
description = "MLpad operator for managing MLOps workflows in Kubernetes environment"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "kopf>=1.38.0",
    "kubernetes>=33.1.0",
    "pytest>=8.4.1",
]
